version: "3.9"

services:
  seq-service:
    image: datalust/seq
    ports:
    - 9004:80
    volumes:
    - rps_seq_data:/data
    environment:
    - ACCEPT_EULA=Y 
  zipkin-service:
    image: openzipkin/zipkin
    ports:
    - 9411:9411

  add-service:
    build:
      context: .
      dockerfile: AddService/Dockerfile


  sub-service:
    build:
      context: .
      dockerfile: SubService/Dockerfile
    deploy:
      replicas: 2

  multi-service:
    build:
      context: .
      dockerfile: MultiplicationService/Dockerfile
    deploy:
      replicas: 2

  history-service:
    build:
      context: .
      dockerfile: HistoryService/Dockerfile
    depends_on:
    - history-db
    ports:
    - 9002:80
  frontend-service:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
    - 9003:80
  history-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "history-database"
      MYSQL_USER: "historydb"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  gateway-service:
    build:
      context: .
      dockerfile: ApiGatewayService/Dockerfile
    ports:
    - 9005:80
volumes:
  rps_seq_data:
   