version: "3.9"

services:
  seq:
    image: datalust/seq
    ports:
    - 9004:80
    volumes:
    - rps_seq_data:/data
    environment:
    - ACCEPT_EULA=Y 
  

  add-service:
    build:
      context: .
      dockerfile: AddService/Dockerfile
    ports:
    - 9000:80
  sub-service:
    build:
      context: .
      dockerfile: SubService/Dockerfile
    ports:
      - 9001:80
  history-service:
    build:
      context: .
      dockerfile: HistoryService/Dockerfile
    depends_on:
    - history-db
    ports:
    - 9002:80
  frontend-service:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
    - 9003:80
  history-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "history-database"
      MYSQL_USER: "historydb"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

volumes:
  rps_seq_data:
   