version: "3.9"

services:
  seq-service:
    image: datalust/seq
    ports:
    - 9004:80
    volumes:
    - rps_seq_data:/data
    environment:
    - ACCEPT_EULA=Y 
  zipkin-service:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
  featurehub-service:
    image: featurehub/party-server:latest
    restart: always
    volumes:
    - featurehub-h2-data:/db
    ports:
    - 8085:8085
  

  add-service:
    build:
      context: .
      dockerfile: AddService/Dockerfile
    deploy:
      replicas: 2

  sub-service:
    build:
      context: .
      dockerfile: SubService/Dockerfile
    deploy:
      replicas: 2

  multi-service:
    build:
      context: .
      dockerfile: MultiplicationService/Dockerfile
    deploy:
      replicas: 2

  history-service:
    build:
      context: .
      dockerfile: HistoryService/Dockerfile

    ports:
    - 9002:80
  frontend-service:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
    - 9003:80
  add-history-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "add-history-database"
      MYSQL_USER: "historydb"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  sub-history-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "sub-history-database"
      MYSQL_USER: "historydb"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  multi-history-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "multi-history-database"
      MYSQL_USER: "historydb"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  gateway-service:
    build:
      context: .
      dockerfile: ApiGatewayService/Dockerfile
    ports:
    - 9005:80
volumes:
  rps_seq_data:
  featurehub-h2-data:
   